name: "Moralis metadata resync"

on:
  schedule:
    - cron: "00 01,13 * * *" # 1 A.M and 1 P.M
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Resync metadata
        env:
          MORALIS_KEY: ${{ secrets.MORALIS_KEY }}
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          pip install -r requirements.txt
          python3 ./src/sync.py